name: Docker Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build API image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.api
        push: false
        tags: rag-api:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build App image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.app
        push: false
        tags: rag-app:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Start services
      run: |
        # Create .env file with dummy values for testing
        echo "OPENAI_API_KEY=sk-test-key" > api/.env
        echo "ENV=test" >> api/.env

        # Start services
        docker-compose up -d

        # Wait for services to be healthy
        timeout 120 bash -c 'until docker-compose ps | grep -q "healthy"; do sleep 2; done'

    - name: Test API health
      run: |
        curl -f http://localhost:8000/health || exit 1

    - name: Test ChromaDB
      run: |
        curl -f http://localhost:8001/api/v1/heartbeat || exit 1

    - name: Show logs on failure
      if: failure()
      run: |
        docker-compose logs

    - name: Cleanup
      if: always()
      run: |
        docker-compose down -v
